name: Deployment Project
on: [push, workflow_dispatch]
jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies with package-lock
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
  deploy_code:
    runs-on: ubuntu-latest
    needs: test_code
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies with package-lock
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying code...."